### ISSUE TITLE
[Proposal] Proxy only mode

### ISSUE THREAD

**Issue by gili-gili** [Chilledheart/yass#1022]
It will be more flexible with proxy only mode and custom listening port.

**Comment by Chilledheart** [comment]
The port could be used already if we bind to a fixed port number. At first, we implemented android app without vpn service.

**Comment by gili-gili** [comment]
So why removed this on Android🤔

**Comment by Chilledheart** [comment]
It is not removed. You can still use it as proxy but at a random port number.

**Comment by gili-gili** [comment]
then how to run yass without TUN enabled🥲  
I don't need to use yass from another device

**Comment by Chilledheart** [comment]
It is not recommended. If you need yass to run as a service, you can run it on a Linux box.

**Comment by gili-gili** [comment]
then how to run yass without TUN enabled🥲  
I don't need to use yass from another device
