### ISSUE TITLE
Feature Requirement: Hide icons and connection status in the top menu bar on macOS.

### ISSUE THREAD

**Issue by UncleUncleWang** [Chilledheart/yass#1064]
I used Yass's SOCKS5 proxy with Clash to run NaiveProxy on my Mac and implemented traffic splitting, which was fantastic—almost the most elegant method. 

However, there's an unfriendly aspect of Yass on macOS: the MacBook's notch display area reduces the available space in the menu bar, and Yass occupies a significant portion, especially with the display of the connection status. 

Yass is excellent, with rapid updates, low memory and CPU usage, and stable performance. 
I am grateful for your outstanding work. 
But the issue of menu bar space consumption is like a thorn in my side, severely affecting the macOS user experience, so please prioritize resolving this issue. 
Once again, thank you!

**Comment by Chilledheart** [comment]
I think we can add a check button box to control the behavior of system status bar for macOS without introducting too many changes.

**Comment by UncleUncleWang** [comment]
> I think we can add a check button box to control the behavior of system status bar for macOS without introducting too many changes.

I think this is a good idea, and the changes will be quick to implement.

**Comment by Chilledheart** [comment]
I don't have my macbook pro at present. It is likely that this change will be landed before 1.13.0 release.

BTW my mail app's notification system for iPhone has been broken for some time. It is expected that replies will be delayed from time to time.

**Comment by UncleUncleWang** [comment]
> I don't have my macbook pro at present. It is likely that this change will be landed before 1.13.0 release.
> 
> BTW my mail app's notification system for iPhone has been broken for some time. It is expected that replies will be delayed from time to time.

I fully understand and I will wait patiently

**Comment by UncleUncleWang** [comment]
> [yass-macos-release-arm64-1.12.3-104-b221de3c-signed.dmg.zip](https://github.com/user-attachments/files/16658749/yass-macos-release-arm64-1.12.3-104-b221de3c-signed.dmg.zip)
> 
> @UncleUncleWang can you give this dmg a try?
> 
> Edited: Intel's version: [yass-macos-release-x86_64-1.12.3-104-6f318127-signed.dmg.zip](https://github.com/user-attachments/files/16659201/yass-macos-release-x86_64-1.12.3-104-6f318127-signed.dmg.zip)

I tried it and it works!
