### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [Chilledheart/yass#1065]
Some Linux distros like Linux Mint and Elementary OS have started putting warnings on, or even hiding unverified flatpaks. Can you verify the flatpak so people can more easily find it? Here is a link to Flathub's verification documentation https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by Chilledheart** [comment]
@Roman19S Thanks. I managed to pair it with the github account. Can you check it out and close this issue if the app is verified?

![image](https://github.com/user-attachments/assets/97b3ff93-a7a0-4f30-aa2c-391140493630)

**Comment by Chilledheart** [comment]
I can now install it from verified subset of flathub:

![image](https://github.com/user-attachments/assets/40673fdf-b286-4fd1-a69f-2d6a876223c3)

**Comment by Chilledheart** [comment]
Flathub website shows a blue check mark now (verified):

![image](https://github.com/user-attachments/assets/0faa53d5-81f0-4d67-b64f-44f06da52f86)

**Comment by Roman19S** [comment]
Thanks for the swift action
