### ISSUE TITLE
Input fields limited in characters, depending on character width

### ISSUE THREAD

**Issue by MaelCrd** [Chilledheart/yass#1086]
### Environment

yass.exe --version
```
yass.exe 1.13.1 type: gui client (windows)
Last Change: 4719ee93f2ccd28dc7bf0f7398138ecabbc41c91-refs/branch-heads/1.13.1{0}
Features: official-build;mingw;arch: x86_64;release;clang 20.0.0;crosscompile;linker lld;ldflags icf;win7;sse3;libc++;mingw ucrt;tcmalloc_minimal (dll);mbedtls;ca-certificates 20240203.3.98;zlib;c-ares;nghttp2;quiche;balsa http parser
TCMALLOC: gperftools 2.15
```

### Description

The input fields are limited in the number of characters, which is problematic in some cases (I use Smartproxy and the username length sometimes exceeds 50 characters).

Moreover, the limit depends on the width of the characters, for example:
- Username : `XXXXXXXXXXXXXXXXXXXX` (20 caractères)
- Username : `iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii` (47 caractères)

Both are at the limit but since the `i` characters are smaller than the `X`, we can enter more characters.

- [X] The bug is reproducible with the latest version of yass
- [X] The yass configuration is minimized to the smallest possible
to reproduce the issue.

**Comment by Chilledheart** [comment]
Thanks for reporting this issue. We can confirm it only occurs on windows version of yass.
