### ISSUE TITLE
per app proxy for android client

### ISSUE THREAD

**Issue by Vnight** [Chilledheart/yass#1106]
Thank you for your contribution on developing this concise app relating to Naiveproxy. Do you have plans to add support for per-app proxy for android client.

**Comment by Chilledheart** [comment]
duplicated to #954.

Android, as well as iOS, is no longer recommended as first class mobile operating system in my nation.
So it is not in current plan yet.

**Comment by Chilledheart** [comment]
And all feature requests in Android/iOS will be moved to second class support.
