### ISSUE TITLE
Not work on Windows Server 2025 with same configuration that works on Server 2022 well

### ISSUE THREAD

**Issue by zhw618** [Chilledheart/yass#1148]
### Environment

the result of the following commands:
  - `naive --version` or the screenshot of About Dialog (for desktop users)
 ~~~cmd
>naive --version
naive 130.0.6723.40
~~~
### Description

Hello,

I’ve been using NaiveProxy without issues on Windows 10. However, after the official release of Windows Server 2025, I encountered problems running NaiveProxy with the same configuration and setup on the new server. The proxy fails to work on Windows Server 2025, even though the same configuration file works fine on Windows 10/Server 2022.

I suspect the issue may be related to enhanced security measures in Windows Server 2025, such as stricter TLS settings or changes in supported cipher suites. Could you please assist in identifying what might be causing this issue? Below is the config_zhw.json file I’ve been using:
~~~json
{
  "listen": "socks://127.0.0.1:10808",
  "proxy": "quic://zhw:zhw@zhw.abc.com:8444",
  "log": ""
}
~~~
Specifically, when running the client with the command:
~~~cmd
C:\>  naive.exe  config_zhw.json
~~~

I would appreciate any guidance or suggestions.

Thank you!

**Comment by zhw618** [comment]
server side ,   the  log : 
~~~bash
[root@vital-kitten-3 ~]# systemctl status caddy2 -l
● caddy2.service - Caddy
   Loaded: loaded (/etc/systemd/system/caddy2.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2024-10-18 22:17:28 CST; 3 weeks 3 days ago
     Docs: https://caddyserver.com/docs/
 Main PID: 16333 (caddy2)
   CGroup: /system.slice/caddy2.service
           └─16333 /usr/bin/caddy2 run --environ --config /etc/caddy/Caddyfile2

Nov 12 00:23:36 vital-kitten-3.localdomain caddy2[16333]: {"level":"error","ts":1731342216.528477,"logger":"http.log.error","msg":"read tcp 66.112.211.205:53410->204.79.197.237:443: read: connection reset by peer","request":{"remote_ip":"125.121.139.127","remote_port":"35234","proto":"HTTP/2.0","method":"CONNECT","host":"204.79.197.237:443","uri":"204.79.197.237:443","headers":{"Padding":["*>'?<,<(<\",@)#+!XXXXXXXXXXXXX"],"Proxy-Authorization":[]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"chenj.home.kg"}},"duration":33.020187992}
Nov 12 01:03:04 vital-kitten-3.localdomain caddy2[16333]: {"level":"error","ts":1731344584.5269713,"logger":"http.log.error","msg":"read tcp 66.112.211.205:23948->108.177.104.188:443: read: connection reset by peer","request":{"remote_ip":"125.121.139.127","remote_port":"35234","proto":"HTTP/2.0","method":"CONNECT","host":"108.177.104.188:443","uri":"108.177.104.188:443","headers":{"Padding":[")\"?<@<<&+#\"*&;;#"],"Proxy-Authorization":[]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"chenj.home.kg"}},"duration":160.182277563}

~~~

**Comment by zhw618** [comment]
Sorry, I sent this issue to a wrong place.

**Comment by Chilledheart** [comment]
@zhw618 Actually, I faced the same issue before with both yass and naiveproxy. You can check with your certificate  ``gci Cert:\LocalMachine\Root`` in powershell. Maybe ISRG X1 Root is missing in your OS. See https://github.com/klzgrad/naiveproxy/issues/612. 

PS this issue is fixed in yass.
