### ISSUE TITLE
为什么要卸载brew?

### ISSUE THREAD

**Issue by fbion** [Chilledheart/yass#1165]
`static bool IsSoftwarePrivatedImpl() {
#if defined(ARCH_CPU_X86_64)
  if (GetCPUType() == CPUType::kIntel)
    return IsFile("/usr/local/bin/brew");
#endif
  return IsFile("/opt/homebrew/bin/brew") || IsDirectory("/opt/homebrew/.git");
}

bool IsSoftwarePrivated() {
  bool ret = IsSoftwarePrivatedImpl();
  if (ret) {
    LOG(WARNING) << "Software Pirated Detected";
    NSAlert* alert = [[NSAlert alloc] init];
    alert.messageText = @("Software aka Homebrew in your mac is pirating yass."
#ifdef OFFICIAL_BUILD
                          "Functionalities will be inavailable due to the censorship of homebrew."
#else
                          "Functionalities might be abnormal due to the censorship of homebrew."
#endif`

**Comment by Chilledheart** [comment]
Homebrew is not WELCOMED here including its users because it's involving politics again my country. We  don't like monkeys. See https://github.com/Chilledheart/yass/issues/1100.

And please file bug in template.

**Comment by Chilledheart** [comment]
If you insist, I can blacklist you from this repository.

**Comment by Chilledheart** [comment]
这个一个有明显政治倾向项目，不符合开源许可证的要求，所以我们不喜欢它。如果你坚持，那我们只能拉黑你。

**Comment by Chilledheart** [comment]
你想修改代码甚至发布的别的平台上，那是你的自由，但是我们不会对代码做任何保证和承诺。我们不会和对我的祖国有政治胁迫的组织和个人提供任何帮助，如果你向解决问题，请你去homebrew平台，是他们先挑起的问题，扩大问题的责任完全在他们身上。如果他们道歉，我们可以考虑这段代码。但是在此之前，我们提供的带数字签名的分发都会保证用户电脑不存在他们的软体。

如果你不回答或者持保留态度，我们只能先将你拉黑。后续想反悔或者有任何进展请私下联系 我的电子邮箱 [keeyou-cn@outlook.com](mailto:keeyou-cn@outlook.com)。

**Comment by Chilledheart** [comment]
> > 你想修改代码甚至发布的别的平台上，那是你的自由，但是我们不会对自行修改/发布的代码做任何保证和承诺。我们不会和对我的祖国有政治胁迫的组织和个人提供任何帮助，如果你想解决问题，请你去homebrew平台，是他们先挑起的问题，问题扩大的责任完全在他们身上。如果他们道歉并承诺不再做出蓄意打击其他国家程序员的行为，我们可以考虑删除这段代码。但是在此之前，我们提供的带数字签名的分发都会保证用户电脑不存在他们的软体。
> > 如果你不回答或者持保留态度，我们只能先将你拉黑。后续想反悔或者有任何进展请私下联系 我的电子邮箱 [keeyou-cn@outlook.com](mailto:keeyou-cn@outlook.com)。
> 
> 一脸懵 我就问问而已 你们之间的事情我不掺合😂

谢谢理解.
