### ISSUE TITLE
[Optional] Add VLESS protocol support

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#650]
VLESS is a stateless lightweight transport protocol, which is divided into inbound and outbound parts, and can be used as a bridge between Xray clients and servers.

Unlike [VMess](https://xtls.github.io/en/config/outbounds/vmess.html), VLESS does not rely on system time, and the authentication method is also UUID.
[https://xtls.github.io/en/config/outbounds/vless.html#outboundconfigurationobject](url)

**Comment by Chilledheart** [comment]
I wonder whether this new protocol has good protection in cryptography as TLS or it relies on a modified TLS network stack which is a bit harder to intergrate with this small project. If it is good in theory and practices, you can ask @naiveproxy folks to do it at first. I am lazy on things which don't bring too much benefits.

And, you can speed chinese if you're chinese guy :-).

**Comment by Chilledheart** [comment]
I don't think TLS over TLS is better compared with naiveproxy. Any way, I need some time to investigate the protocol.

**Comment by Chilledheart** [comment]
It is only required by Legacy Platforms.

Close all feature requests to Legacy Platforms for now.
