### ISSUE TITLE
[Mac] Add background startup daemon mode

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#672]
Little mode

**Comment by Chilledheart** [comment]
I guess you can use yass_cli for systemd (linux)/launchctl daemon (macOS) for your case.

**Comment by Chilledheart** [comment]
Yes, for systemd (linux) you can start with [this service file][yass]. For macOS, you can refer to [the official manual of launchctl][launchctl]. And for windows, you can start yass (i refer yass_cli to cli client instead) in background by clicking "autostart" checkbox which makes yass start in quite mode.  If you have troubles with yass_cli binaries in release note page, you can refer to this [building] document to build yass_cli from source code.

So for most cases, you don't need real daemon mode.

[yass]: https://github.com/Chilledheart/yass/blob/develop/yass.service
[launchctl]: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
[building]: https://github.com/Chilledheart/yass/blob/develop/BUILDING.md

**Comment by Chilledheart** [comment]
Which architecture do you use, arm64 or x64? Can you give this dmg a try?
[yass-macos-release-arm64-1.5.19-10-g74573f93.dmg.zip](https://github.com/Chilledheart/yass/files/13961223/yass-macos-release-arm64-1.5.19-10-g74573f93.dmg.zip)
