### ISSUE TITLE
[iOS GUI] Move the start and stop layouts to the top to minimize false touches. 

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#724]
Device: iphone X - 15 latest
Trigger condition: Fast application switching

**Comment by Chilledheart** [comment]
You can start/stop the connection in Settings app's VPN choice.

As UI changes, I am not familiar with iOS. It might take some time.

**Comment by Chilledheart** [comment]
New UI layout:

![iphone_5 5_Simulator Screenshot - iPhone 5 5  Display - 2024-02-01 at 12 14 16](https://github.com/Chilledheart/yass/assets/54673341/7f289eba-d426-4c60-9a8e-afe62e6872a6)
