### ISSUE TITLE
Add customizable DOT /DOH support

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#774]
Designed to protect user privacy by preventing man-in-the-middle attacks and controlling DNS data.

**Comment by Chilledheart** [comment]
Give a look at https://github.com/c-ares/c-ares/issues/612

**Comment by Chilledheart** [comment]
And for iOS, you can apply the profile for the whole system. See https://github.com/DigitaleGesellschaft/DNS-Resolver/commit/08386e6bf43d46c3b83deed45bc37ac1fcc5cad4

**Comment by Chilledheart** [comment]
curl has doh builtin https://github.com/curl/curl/blob/cd937651448b0176dcda544eb6720cfe894573fb/lib/doh.h and https://github.com/curl/curl/blob/cd937651448b0176dcda544eb6720cfe894573fb/lib/doh.c. we can start from it.

**Comment by Chilledheart** [comment]
Chromium's DOH support page: https://www.chromium.org/developers/dns-over-https/ https://simpledns.plus/kb/195-how-to-enable-dns-over-https-doh-in-chrome.

**Comment by Chilledheart** [comment]
rfc for doh: https://datatracker.ietf.org/doc/html/rfc8484

**Comment by Chilledheart** [comment]
rfc for dot: https://datatracker.ietf.org/doc/html/rfc7858

**Comment by Chilledheart** [comment]
DoH will be added in #832 and available in commandline "--doh_url <URL>".

**Comment by Chilledheart** [comment]
iOS Support is added in #833.
