### ISSUE TITLE
stupid question about how to forward traffic to remote socks proxy via yass gui ?

### ISSUE THREAD

**Issue by ccddos** [Chilledheart/yass#943]
here is my config, but it seems not work ?

for example, 
i specific the proxy server to localhost:3080
and i want to access  internet via socks5 proxy on desktop-v3l44l1:10809

![image](https://github.com/Chilledheart/yass/assets/135016091/ac9cff48-17cb-4984-8932-20e5355407b6)

**Comment by ccddos** [comment]
Also I  do not find suitable cipher in the gui 
![image](https://github.com/Chilledheart/yass/assets/135016091/57f72b71-51d2-493d-89b5-7f0086a08f6e)

**Comment by Chilledheart** [comment]
yass doesn't support socks5 as upstream server because it servers as a socks5 server and it is designed that the downstream supports socks5.

For your case, you can setup and use your remote socks5 server in Internet Options of Control Panel directly.

**Comment by ccddos** [comment]
got it, thanks

**Comment by Chilledheart** [comment]
It will be considered if socks5 upstream is valuable to be supported.

**Comment by ccddos** [comment]
@Chilledheart 
I use yass as a single point for config socks5 proxy, which means i do not need to change all proxy config when my proxy server ip change

**Comment by Chilledheart** [comment]
Thanks for the explaination. Added #944 to track it.

**Comment by Chilledheart** [comment]
I have made some progress in #944 but the code is pretty new and needs tests. Let me know if there is issues or problems when using it with other SOCKS servers. This feature will be delivered in Next point release.

**Comment by Chilledheart** [comment]
One thing to comment, for the simility, the new SOCKS cipher methods don't accept any authentific method even you enter username and password in the text fields.

**Comment by Chilledheart** [comment]
> One thing to comment, for the simility, the new SOCKS cipher methods don't accept any authentific method even you enter username and password in the text fields.

It will be supported for "Username/Password Authentication for SOCKS V5" in SOCKS5/SOCKS5H cipher. see https://github.com/Chilledheart/yass/pull/951

**Comment by ccddos** [comment]
@Chilledheart Thanks, i have test the latest version and it works perfectly !

**Comment by Chilledheart** [comment]
> @Chilledheart Thanks, i have test the latest version and it works perfectly !

nice to hear that.
