### ISSUE TITLE
[android] split tunnel apps

### ISSUE THREAD

**Issue by legiz-ru** [Chilledheart/yass#954]
split tunnel for specified applications, like a Wireguard or Shadowsocks android client

**Comment by Chilledheart** [comment]
It is largely platform-dependent feature. We'll look at it if it feed large scale of people's need.

**Comment by scychina** [comment]
We also want to support features such as accessing specified apps or domains.  thanks

**Comment by scychina** [comment]
Okay, thank you. I understand

**Comment by Chilledheart** [comment]
Thanks for understanding. It is just not our goal.

**Comment by Chilledheart** [comment]
Close all feature requests to Legacy Platforms for now.
